// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbGGXxPO8SQOxM98a9jP7O_nFKJzBdUoY',
    appId: '1:187264685778:web:7cfcebebb7adde0a0f7f0b',
    messagingSenderId: '187264685778',
    projectId: 'plat-dbe12',
    authDomain: 'plat-dbe12.firebaseapp.com',
    databaseURL: 'https://plat-dbe12-default-rtdb.firebaseio.com',
    storageBucket: 'plat-dbe12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbNsH1r8Zz0sg_Hh27awTmGCz0H4Hc5ds',
    appId: '1:187264685778:android:468a600d4cc2d34a0f7f0b',
    messagingSenderId: '187264685778',
    projectId: 'plat-dbe12',
    databaseURL: 'https://plat-dbe12-default-rtdb.firebaseio.com',
    storageBucket: 'plat-dbe12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXGzpv4ZWp79dhm2fZfFPt4ynoXvQm_ms',
    appId: '1:187264685778:ios:5b8f22dfdcebc81b0f7f0b',
    messagingSenderId: '187264685778',
    projectId: 'plat-dbe12',
    databaseURL: 'https://plat-dbe12-default-rtdb.firebaseio.com',
    storageBucket: 'plat-dbe12.appspot.com',
    iosBundleId: 'com.example.plat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXGzpv4ZWp79dhm2fZfFPt4ynoXvQm_ms',
    appId: '1:187264685778:ios:5b8f22dfdcebc81b0f7f0b',
    messagingSenderId: '187264685778',
    projectId: 'plat-dbe12',
    databaseURL: 'https://plat-dbe12-default-rtdb.firebaseio.com',
    storageBucket: 'plat-dbe12.appspot.com',
    iosBundleId: 'com.example.plat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbGGXxPO8SQOxM98a9jP7O_nFKJzBdUoY',
    appId: '1:187264685778:web:b6a5eb2c7fcd293f0f7f0b',
    messagingSenderId: '187264685778',
    projectId: 'plat-dbe12',
    authDomain: 'plat-dbe12.firebaseapp.com',
    databaseURL: 'https://plat-dbe12-default-rtdb.firebaseio.com',
    storageBucket: 'plat-dbe12.appspot.com',
  );
}
